# automatically generated by the FlatBuffers compiler, do not modify

# namespace: dataprotocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BytesValue(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BytesValue()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBytesValue(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BytesValue
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BytesValue
    def Value(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # BytesValue
    def ValueAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # BytesValue
    def ValueLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BytesValue
    def ValueIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def BytesValueStart(builder): builder.StartObject(1)
def Start(builder):
    return BytesValueStart(builder)
def BytesValueAddValue(builder, value): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)
def AddValue(builder, value):
    return BytesValueAddValue(builder, value)
def BytesValueStartValueVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartValueVector(builder, numElems):
    return BytesValueStartValueVector(builder, numElems)
def BytesValueEnd(builder): return builder.EndObject()
def End(builder):
    return BytesValueEnd(builder)
try:
    from typing import List
except:
    pass

class BytesValueT(object):

    # BytesValueT
    def __init__(self):
        self.value = None  # type: List[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        bytesValue = BytesValue()
        bytesValue.Init(buf, pos)
        return cls.InitFromObj(bytesValue)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, bytesValue):
        x = BytesValueT()
        x._UnPack(bytesValue)
        return x

    # BytesValueT
    def _UnPack(self, bytesValue):
        if bytesValue is None:
            return
        if not bytesValue.ValueIsNone():
            if np is None:
                self.value = []
                for i in range(bytesValue.ValueLength()):
                    self.value.append(bytesValue.Value(i))
            else:
                self.value = bytesValue.ValueAsNumpy()

    # BytesValueT
    def Pack(self, builder):
        if self.value is not None:
            if np is not None and type(self.value) is np.ndarray:
                value = builder.CreateNumpyVector(self.value)
            else:
                BytesValueStartValueVector(builder, len(self.value))
                for i in reversed(range(len(self.value))):
                    builder.PrependByte(self.value[i])
                value = builder.EndVector()
        BytesValueStart(builder)
        if self.value is not None:
            BytesValueAddValue(builder, value)
        bytesValue = BytesValueEnd(builder)
        return bytesValue
