# automatically generated by the FlatBuffers compiler, do not modify

# namespace: dataprotocol

class DataType(object):
    NONE = 0
    LONG = 1
    BOOLEAN = 2
    DOUBLE = 3
    STRING = 4
    BINARY = 5
    STRING_RLE = 6
