# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='table_store_filter.proto',
  package='com.aliyun.tablestore.protocol',
  serialized_pb='\n\x18table_store_filter.proto\x12\x1e\x63om.aliyun.tablestore.protocol\"\xc0\x01\n\x17SingleColumnValueFilter\x12\x42\n\ncomparator\x18\x01 \x02(\x0e\x32..com.aliyun.tablestore.protocol.ComparatorType\x12\x13\n\x0b\x63olumn_name\x18\x02 \x02(\t\x12\x14\n\x0c\x63olumn_value\x18\x03 \x02(\x0c\x12\x19\n\x11\x66ilter_if_missing\x18\x04 \x02(\x08\x12\x1b\n\x13latest_version_only\x18\x05 \x02(\x08\"\x9e\x01\n\x1a\x43ompositeColumnValueFilter\x12\x43\n\ncombinator\x18\x01 \x02(\x0e\x32/.com.aliyun.tablestore.protocol.LogicalOperator\x12;\n\x0bsub_filters\x18\x02 \x03(\x0b\x32&.com.aliyun.tablestore.protocol.Filter\"7\n\x16\x43olumnPaginationFilter\x12\x0e\n\x06offset\x18\x01 \x02(\x05\x12\r\n\x05limit\x18\x02 \x02(\x05\"R\n\x06\x46ilter\x12\x38\n\x04type\x18\x01 \x02(\x0e\x32*.com.aliyun.tablestore.protocol.FilterType\x12\x0e\n\x06\x66ilter\x18\x02 \x02(\x0c*a\n\nFilterType\x12\x1a\n\x16\x46T_SINGLE_COLUMN_VALUE\x10\x01\x12\x1d\n\x19\x46T_COMPOSITE_COLUMN_VALUE\x10\x02\x12\x18\n\x14\x46T_COLUMN_PAGINATION\x10\x03*\x80\x01\n\x0e\x43omparatorType\x12\x0c\n\x08\x43T_EQUAL\x10\x01\x12\x10\n\x0c\x43T_NOT_EQUAL\x10\x02\x12\x13\n\x0f\x43T_GREATER_THAN\x10\x03\x12\x14\n\x10\x43T_GREATER_EQUAL\x10\x04\x12\x10\n\x0c\x43T_LESS_THAN\x10\x05\x12\x11\n\rCT_LESS_EQUAL\x10\x06*4\n\x0fLogicalOperator\x12\n\n\x06LO_NOT\x10\x01\x12\n\n\x06LO_AND\x10\x02\x12\t\n\x05LO_OR\x10\x03')

_FILTERTYPE = descriptor.EnumDescriptor(
  name='FilterType',
  full_name='com.aliyun.tablestore.protocol.FilterType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='FT_SINGLE_COLUMN_VALUE', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FT_COMPOSITE_COLUMN_VALUE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FT_COLUMN_PAGINATION', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=557,
  serialized_end=654,
)


_COMPARATORTYPE = descriptor.EnumDescriptor(
  name='ComparatorType',
  full_name='com.aliyun.tablestore.protocol.ComparatorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='CT_EQUAL', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CT_NOT_EQUAL', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CT_GREATER_THAN', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CT_GREATER_EQUAL', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CT_LESS_THAN', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CT_LESS_EQUAL', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=657,
  serialized_end=785,
)


_LOGICALOPERATOR = descriptor.EnumDescriptor(
  name='LogicalOperator',
  full_name='com.aliyun.tablestore.protocol.LogicalOperator',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='LO_NOT', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LO_AND', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LO_OR', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=787,
  serialized_end=839,
)


FT_SINGLE_COLUMN_VALUE = 1
FT_COMPOSITE_COLUMN_VALUE = 2
FT_COLUMN_PAGINATION = 3
CT_EQUAL = 1
CT_NOT_EQUAL = 2
CT_GREATER_THAN = 3
CT_GREATER_EQUAL = 4
CT_LESS_THAN = 5
CT_LESS_EQUAL = 6
LO_NOT = 1
LO_AND = 2
LO_OR = 3



_SINGLECOLUMNVALUEFILTER = descriptor.Descriptor(
  name='SingleColumnValueFilter',
  full_name='com.aliyun.tablestore.protocol.SingleColumnValueFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='comparator', full_name='com.aliyun.tablestore.protocol.SingleColumnValueFilter.comparator', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='column_name', full_name='com.aliyun.tablestore.protocol.SingleColumnValueFilter.column_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='column_value', full_name='com.aliyun.tablestore.protocol.SingleColumnValueFilter.column_value', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filter_if_missing', full_name='com.aliyun.tablestore.protocol.SingleColumnValueFilter.filter_if_missing', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='latest_version_only', full_name='com.aliyun.tablestore.protocol.SingleColumnValueFilter.latest_version_only', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=61,
  serialized_end=253,
)


_COMPOSITECOLUMNVALUEFILTER = descriptor.Descriptor(
  name='CompositeColumnValueFilter',
  full_name='com.aliyun.tablestore.protocol.CompositeColumnValueFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='combinator', full_name='com.aliyun.tablestore.protocol.CompositeColumnValueFilter.combinator', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sub_filters', full_name='com.aliyun.tablestore.protocol.CompositeColumnValueFilter.sub_filters', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=256,
  serialized_end=414,
)


_COLUMNPAGINATIONFILTER = descriptor.Descriptor(
  name='ColumnPaginationFilter',
  full_name='com.aliyun.tablestore.protocol.ColumnPaginationFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='offset', full_name='com.aliyun.tablestore.protocol.ColumnPaginationFilter.offset', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='limit', full_name='com.aliyun.tablestore.protocol.ColumnPaginationFilter.limit', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=416,
  serialized_end=471,
)


_FILTER = descriptor.Descriptor(
  name='Filter',
  full_name='com.aliyun.tablestore.protocol.Filter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='com.aliyun.tablestore.protocol.Filter.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filter', full_name='com.aliyun.tablestore.protocol.Filter.filter', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=473,
  serialized_end=555,
)

_SINGLECOLUMNVALUEFILTER.fields_by_name['comparator'].enum_type = _COMPARATORTYPE
_COMPOSITECOLUMNVALUEFILTER.fields_by_name['combinator'].enum_type = _LOGICALOPERATOR
_COMPOSITECOLUMNVALUEFILTER.fields_by_name['sub_filters'].message_type = _FILTER
_FILTER.fields_by_name['type'].enum_type = _FILTERTYPE
DESCRIPTOR.message_types_by_name['SingleColumnValueFilter'] = _SINGLECOLUMNVALUEFILTER
DESCRIPTOR.message_types_by_name['CompositeColumnValueFilter'] = _COMPOSITECOLUMNVALUEFILTER
DESCRIPTOR.message_types_by_name['ColumnPaginationFilter'] = _COLUMNPAGINATIONFILTER
DESCRIPTOR.message_types_by_name['Filter'] = _FILTER

class SingleColumnValueFilter(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SINGLECOLUMNVALUEFILTER
  
  # @@protoc_insertion_point(class_scope:com.aliyun.tablestore.protocol.SingleColumnValueFilter)

class CompositeColumnValueFilter(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMPOSITECOLUMNVALUEFILTER
  
  # @@protoc_insertion_point(class_scope:com.aliyun.tablestore.protocol.CompositeColumnValueFilter)

class ColumnPaginationFilter(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COLUMNPAGINATIONFILTER
  
  # @@protoc_insertion_point(class_scope:com.aliyun.tablestore.protocol.ColumnPaginationFilter)

class Filter(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FILTER
  
  # @@protoc_insertion_point(class_scope:com.aliyun.tablestore.protocol.Filter)

# @@protoc_insertion_point(module_scope)
