# automatically generated by the FlatBuffers compiler, do not modify

# namespace: timeseries

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FlatBufferRows(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FlatBufferRows()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFlatBufferRows(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FlatBufferRows
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FlatBufferRows
    def RowGroups(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from timeseries.FlatBufferRowGroup import FlatBufferRowGroup
            obj = FlatBufferRowGroup()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FlatBufferRows
    def RowGroupsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FlatBufferRows
    def RowGroupsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def FlatBufferRowsStart(builder):
    builder.StartObject(1)

def Start(builder):
    FlatBufferRowsStart(builder)

def FlatBufferRowsAddRowGroups(builder, rowGroups):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(rowGroups), 0)

def AddRowGroups(builder, rowGroups):
    FlatBufferRowsAddRowGroups(builder, rowGroups)

def FlatBufferRowsStartRowGroupsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRowGroupsVector(builder, numElems):
    return FlatBufferRowsStartRowGroupsVector(builder, numElems)

def FlatBufferRowsEnd(builder):
    return builder.EndObject()

def End(builder):
    return FlatBufferRowsEnd(builder)
